### ISSUE TITLE
Week 41 TODO list

### ISSUE THREAD

**Issue by noel5550** [noel5550/Projet_Algo_Struct_3#1]
# Week 41 TODO list
## @Tee-veeNovae
- [ ] Signature de Grid
## @noel5550
- [ ] Signature de Tile
- [ ] Signature de Player
